FROM python:3.12-slim

WORKDIR /app

ARG RELEASE_VERSION=k8s-v1

ENV RELEASE_VERSION=${RELEASE_VERSION}

COPY requirements-serving.txt .

RUN pip install \
    --no-cache-dir \
    -r requirements-serving.txt

COPY src/ ./src/
COPY models/ ./models/

EXPOSE 8000

CMD ["uvicorn", "src.api_k8s:app", "--host", "0.0.0.0", "--port", "8000"]
